const {contextBridge,ipcRenderer}=require("electron");
contextBridge.exposeInMainWorld("desktop",{
 auth:{status:()=>ipcRenderer.invoke("auth:status"),current:()=>ipcRenderer.invoke("auth:current"),register:p=>ipcRenderer.invoke("auth:register",p),login:p=>ipcRenderer.invoke("auth:login",p),logout:()=>ipcRenderer.invoke("auth:logout"),clearData:()=>ipcRenderer.invoke("auth:clear-data")},
 uiSettings:{get:()=>ipcRenderer.invoke("ui-settings:get"),set:v=>ipcRenderer.invoke("ui-settings:set",v),onUpdated:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("ui-settings:updated",fn);return()=>ipcRenderer.removeListener("ui-settings:updated",fn)}},
 users:{list:()=>ipcRenderer.invoke("users:list"),create:p=>ipcRenderer.invoke("users:create",p),update:p=>ipcRenderer.invoke("users:update",p),delete:id=>ipcRenderer.invoke("users:delete",id),onUpdated:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("user:updated",fn);return()=>ipcRenderer.removeListener("user:updated",fn)}},
 plans:{list:()=>ipcRenderer.invoke("plans:list")},
 apps:{get:()=>ipcRenderer.invoke("apps:get")},
 customLimits:{get:userId=>ipcRenderer.invoke("custom-limits:get",userId),set:p=>ipcRenderer.invoke("custom-limits:set",p),onUpdated:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("custom-limits:updated",fn);return()=>ipcRenderer.removeListener("custom-limits:updated",fn)}},customServices:{get:userId=>ipcRenderer.invoke("custom-services:get",userId),add:p=>ipcRenderer.invoke("custom-services:add",p),remove:p=>ipcRenderer.invoke("custom-services:remove",p),onUpdated:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("custom-services:updated",fn);return()=>ipcRenderer.removeListener("custom-services:updated",fn)}},
 accounts:{get:id=>ipcRenderer.invoke("accounts:get",id),add:p=>ipcRenderer.invoke("accounts:add",p),remove:p=>ipcRenderer.invoke("accounts:remove",p),onUpdated:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("accounts:updated",fn);return()=>ipcRenderer.removeListener("accounts:updated",fn)},onRemoved:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("accounts:removed",fn);return()=>ipcRenderer.removeListener("accounts:removed",fn)},onCleared:cb=>{const fn=()=>cb();ipcRenderer.on("accounts:cleared",fn);return()=>ipcRenderer.removeListener("accounts:cleared",fn)}},
 view:{preload:p=>ipcRenderer.invoke("view:preload",p),open:p=>ipcRenderer.invoke("view:open",p),close:()=>ipcRenderer.invoke("view:close"),reload:()=>ipcRenderer.invoke("view:reload")},
 window:{minimize:()=>ipcRenderer.invoke("window:minimize"),maximize:()=>ipcRenderer.invoke("window:maximize"),close:()=>ipcRenderer.invoke("window:close")},app:{quit:()=>ipcRenderer.invoke("app:quit")},
 sidebar:{show:()=>ipcRenderer.invoke("sidebar:show"),toggle:()=>ipcRenderer.invoke("sidebar:toggle"),minimize:()=>ipcRenderer.invoke("sidebar:minimize"),resize:height=>ipcRenderer.invoke("sidebar:resize",height),settingsOpen:()=>ipcRenderer.invoke("settings:open"),settingsClose:()=>ipcRenderer.invoke("settings:close"),onViewState:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("view:state",fn);return()=>ipcRenderer.removeListener("view:state",fn)},onSettingsState:cb=>{const fn=(_e,a)=>cb(a);ipcRenderer.on("settings:state",fn);return()=>ipcRenderer.removeListener("settings:state",fn)}}
});
